### ISSUE TITLE
All links don't work

### ISSUE THREAD

**Issue by we1cao** [IIT-PAVIS/ExHistCNN#1]
All links don't work

**Comment by yiming107** [comment]
Hi Wei,

I just updated all the links again. It should work now. Unfortunately on OneDrive I can only keep the link alive for 1 month due to the institute regulation. I will try to migrate all the data to Google Drive soon, so the links can work for long term.

Best,
Y.

**Comment by yiming107** [comment]
Resolved with updated links to all files.

**Comment by trebladev** [comment]
> Resolved with updated links to all files.

The links still don't work now, can you upload it again
thanks
